/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Backbone, _, Drupal) {
  Drupal.addToCart.AddToCartView = Backbone.View.extend({
    selectedVariation: '',
    selectedAttributes: [],
    variations: {},
    attributes: {},
    initialize: function initialize() {
      this.selectedVariation = this.model.getDefaultVariation();
      this.variations = this.model.getVariations();
      this.attributes = this.model.getAttributes();

      var defaultVariation = this.variations[this.selectedVariation];
      var self = this;
      _.each(this.attributes, function (attribute, i) {
        var attributeFieldName = 'attribute_' + attribute.id;
        if (defaultVariation.hasOwnProperty(attributeFieldName)) {
          self.selectedAttributes[attributeFieldName] = defaultVariation[attributeFieldName];
        }
      });
      this.render();
    },

    events: {
      'click [name="addToCart"]': 'addToCart',
      'change input[type="radio"]': 'onAttributeChange',
      'change select': 'onAttributeChange'
    },
    onAttributeChange: function onAttributeChange(event) {
      var value = event.target.value;
      var attribute = event.target.name;
      this.selectedAttributes[attribute] = value;
    },
    resolveSelectedVariation: function resolveSelectedVariation() {
      var selectedAttributes = this.selectedAttributes;
      var attributes = this.attributes;
      var variations = Object.values(this.variations);

      var selectedVariation = variations.filter(function (variation) {
        return attributes.every(function (attribute) {
          var fieldName = 'attribute_' + attribute.id;
          return variation.hasOwnProperty(fieldName) && variation[fieldName].toString() === selectedAttributes[fieldName].toString();
        });
      });
      this.selectedVariation = selectedVariation[0].uuid;
    },
    addToCart: function addToCart() {
      this.resolveSelectedVariation();
      var endpoint = Drupal.url('cart/add?_format=json');
      fetch(endpoint, {
        credentials: 'include',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        method: 'POST',
        body: JSON.stringify([{
          purchased_entity_type: 'commerce_product_variation',
          purchased_entity_id: this.variations[this.selectedVariation].variation_id,
          quantity: 1
        }])
      }).then(function (res) {}).then(function () {
        return Drupal.cartFlyout.fetchCarts();
      });
    },
    generateSelect: function generateSelect(attribute) {},
    render: function render() {
      var _this = this;

      var count = Object.keys(this.variations).length;
      if (count === 1) {
        this.$el.html('<div><input name="addToCart" type="submit" value="Add to cart"/></div>');
      } else {
        var html = [];
        this.attributes.forEach(function (entry) {
          if (entry.element_type === 'select') {
            var selectCompiled = _.template('<div class="form-group">' + '<label class="control-label"><%= label %></label>' + '<select name="attribute_<%= attributeId %>" class="form-control">' + '<% _.each(attributeValues, function(currentValue, key) { %>' + '<option value="<%= currentValue.attribute_value_id %>" <%= (activeValue === currentValue.attribute_value_id) ? \'selected\' : \'\' %>><%= currentValue.name %></option>' + '<% }); %>' + '</select></div>');
            html.push(selectCompiled({
              label: entry.label,
              attributeId: entry.id,
              attributeValues: entry.values,
              activeValue: _this.selectedAttributes[entry.id]
            }));
          } else if (entry.element_type === 'radios') {
            var radiosCompiled = _.template('<div class="form-group">' + '<label class="control-label"><%= label %></label>' + '<% _.each(attributeValues, function(currentValue, key) { %>' + '<div class="radio">' + '<label><input type="radio" class="form-radio" name="attribute_<%= attributeId %>" value="<%= currentValue.attribute_value_id %>" <%= (activeValue === currentValue.attribute_value_id) ? \'checked\' : \'\' %>/><%= currentValue.name %></label>' + '</div>' + '<% }); %>' + '</div>');
            html.push(radiosCompiled({
              label: entry.label,
              attributeId: entry.id,
              attributeValues: entry.values,
              activeValue: _this.selectedAttributes[entry.id]
            }));
          } else if (entry.element_type === 'commerce_product_rendered_attribute') {

            var _radiosCompiled = _.template('<div class="form-group">' + '<label class="control-label"><%= label %></label>' + '<% _.each(attributeValues, function(currentValue, key) { %>' + '<div class="radio">' + '<label><input type="radio" class="form-radio" name="attribute_<%= attributeId %>" value="<%= currentValue.attribute_value_id %>" <%= (activeValue === currentValue.attribute_value_id) ? \'checked\' : \'\' %>/>' + '<div class="swatch--square" style="background-color: <%= currentValue.field_color.color %>; width: 30px; height: 30px;"></div>' + '</label>' + '</div>' + '<% }); %>' + '</div>');
            html.push(_radiosCompiled({
              label: entry.label,
              attributeId: entry.id,
              attributeValues: entry.values,
              activeValue: _this.selectedAttributes[entry.id]
            }));
          }
        });

        html.push('<div><input name="addToCart" type="submit" value="Add to cart"/></div>');
        var compiled = _.template(html.join(''));
        this.$el.html(compiled);
      }
    }
  });
})(Backbone, _, Drupal);